export enum EProjectAction {
  UPDATE_PROJECT = 'UPDATE_PROJECT',
  REMOVE_PROJECT = 'REMOVE_PROJECT',

  ADD_CONTRIBUTOR = 'ADD_CONTRIBUTOR',
  REMOVE_CONTRIBUTOR = 'REMOVE_CONTRIBUTOR',
  UPDATE_CONTRIBUTOR_ROLE = 'UPDATE_CONTRIBUTOR_ROLE',
}
